var HDWalletProvider = require("truffle-hdwallet-provider");

// Test mnemonic created with MetaMask
var testMnemonic = "butter expose joke orbit pair general alley meadow detect thumb manage jungle";

module.exports = {
    networks: {
        development: {
            host: "localhost",
            port: 7545,
            network_id: "*",
			gas: 6720000
        },

		ropsten: {
			provider: function() {
				// Note, the first address generated by the mnemonic will be used
				return new HDWalletProvider(testMnemonic, 
					"https://ropsten.infura.io/K4judMJU1OZXP97v0R75", 1)
			},
			network_id: "*",
			// Need to set gas limit between "out of gas limit" and "exceeding block gas limit"
			// Default is 4712388, which eventually causes "exceeds block gas limit"
			gas: 4700000

		}
    }
};
