var HDWalletProvider = require("truffle-hdwallet-provider");
var fs = require("fs");

/*
 * mnemonic will be saved in external file, which will be securely kept in each developer's local storage
 * A developer is responsible for creating "mnemonic.txt" accordingly since it won't be managed under git.
 */
var mnemonic;

fs.readFile('./mnemonic.txt', 'utf8', function (err,data) {
	if (err) {
		return console.log(err);
	}
	mnemonic = data;
	//console.log(mnemonic);
});


module.exports = {
    networks: {
        development: {
            host: "localhost",
            port: 7545,
            network_id: "*",
			gas: 6720000
        },

		ropsten: {
			provider: function() {
				// Note, the first address generated by the mnemonic will be used
				return new HDWalletProvider(mnemonic, 
					"https://ropsten.infura.io/K4judMJU1OZXP97v0R75", 1)
			},
			network_id: "*",
			// Need to set gas limit between "out of gas limit" and "exceeding block gas limit"
			// Default is 4712388, which eventually causes "exceeds block gas limit"
			gas: 4700000

		}
    }
};
